### ISSUE TITLE
ActionCableを使用したい。

### ISSUE THREAD

**Issue by yoshi-dai** [yoshi-dai/ballmate#38]
- 質問内容・実現したいこと
ActionCableを使用してリアルタイムチャット機能を作成したく、まず動作確認のためにメッセージとして入力したテキストをalertで画面に表示したいです。

- 現状発生している問題・エラーメッセージ
アラートが表示されない。エラーメッセージは出ていません。

- どの処理までうまく動いているのか
viewページに置いたinputタグに入力してEnterキーを押すことをきっかけにconsole.logでテキストを表示することはできました。
- 該当のソースコード
app/javascript/channels/chat_channel.js
```
import consumer from "./consumer"

const chatChannel = consumer.subscriptions.create("ChatChannel", {
  connected() {
    // Called when the subscription is ready for use on the server
  },

  disconnected() {
    // Called when the subscription has been terminated by the server
  },

  received(data) {
　console.log(data); →   何も表示されませんでした。
    return alert(data['message']);
  },

  speak: function(message) {
　console.log(message); → 入力したテキストが表示されました。
    return this.perform('speak', {message: message});
  }
});

$(document).on('keypress', '[data-behavior~=room_speaker]', function(event) {
  if (event.key === 'Enter') {
    console.log(event.target.value);→ 入力したテキストが表示されました。
    chatChannel.speak(event.target.value);
    console.log(chatChannel.speak(event.target.value));→trueが表示されました。
    event.target.value = '';
    event.preventDefault();
  }
});
```

app/channels/chat_channel.rb
```
class ChatChannel < ApplicationCable::Channel
  def subscribed
    stream_from "chat_channel"
  end

  def unsubscribed
    # Any cleanup needed when channel is unsubscribed
  end

  def speak(data)
    ActionCable.server.broadcast 'chat_channel', message: data['message']
  end
end
```

ビュー画面に置いたフォーム
```
<form>
    <label>Say something:</label><br>
    <input type="text" data-behavior="room_speaker">
  </form>
```

- エラーから考えられる原因
```
  def speak(data)
    ActionCable.server.broadcast 'chat_channel', message: data['message']
  end
```
の部分で、受け取ったdataをapp/javascript/channels/chat_channel.jsのreceived(data)〜にブロードキャストできていないのかな？と思います。

- 試したこと
この場合、return this.perform('speak', {message: message});以降をどのように検証していけばいいかわからなかったです。

**Comment by Tsuchiya2** [comment]
以下、ChatGPTにIssue内容を投げた結果の共有になります。

---

現在の問題点は speak(data) メソッドから received(data) へのデータの伝達がうまく行っていない可能性が高そうです。

この問題のデバッグは少々難しいかもしれませんが、次のいくつかのステップを試してみてください。

1. speak(data) メソッドが呼び出されているか確認する
Ruby on Railsのロガーを利用して、speak(data) メソッドが正しく呼び出されているかを確認します。これを行うためには、次の行を speak(data) メソッドに追加します。

```ruby
def speak(data)
  Rails.logger.info "Speak called with #{data['message']}"
  ActionCable.server.broadcast 'chat_channel', message: data['message']
end
```

これで、メソッドが呼び出されたときに、そのメッセージがログに出力されるはずです。

2. メッセージが正しくブロードキャストされているか確認する
これもロガーを利用して行うことができます。次の行を speak(data) メソッドに追加します。
```ruby
def speak(data)
  Rails.logger.info "Speak called with #{data['message']}"
  result = ActionCable.server.broadcast 'chat_channel', message: data['message']
  Rails.logger.info "Broadcast result: #{result}"
end
```
ここで、result はブロードキャストが成功したら配信された接続数を返すはずです。これでブロードキャストが成功しているかを確認することができます。

3. ブラウザ側で received(data) が呼び出されているか確認する
ブラウザのJavaScriptコンソールを開き、次のように入力してみてください。
```javascript
chatChannel.received({message: "Test"})
```
これにより received(data) メソッドが手動で呼び出され、Test というメッセージがアラートとして表示されるはずです。これで received(data) メソッドが正しく動作しているかを確認することができます。

これらのステップを試した結果、どの部分が問題であるかが明らかになると思います。それによって、次のデバッグステップを決定することができます。

どうぞお試しください。

**Comment by yoshi-dai** [comment]
```
def speak(data)
  Rails.logger.info "Speak called with #{data['message']}"
  result = ActionCable.server.broadcast 'chat_channel', message: data['message']
  Rails.logger.info "Broadcast result: #{result}"
end
```
の結果、result = ActionCable.server.broadcast 'chat_channel', message: data['message']の第二引数がハッシュでなかったことが原因でした。
