### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [yoshi-dai/ballmate#74]
ご提出ありがとうございます。
以下の観点からレビューを行います。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

---

### １について
概ねMVP機能は満たせているように感じました。

### ２について
やや行数が多くなっているアクションが散見されたので、Rubocopを通したり、別途メソッドを切り出せないか検討してみましょう。

### ３について
- テーブル数も一定数ある点は良いと思いました。
- ルーティングの部分でいうと、できる限りresourceベースのルーティングを組むようにしましょう。
- 複数のテーブルが１つのアクション内で作成・更新等される場合はトランザクションを使うようにしましょう。
- コントローラーにおいて共通化できる部分はbefore_action化やprivate以下にメソッドを使って呼び出すなどしましょう。また、Fat Controllerになりそうな傾向を感じたので、適宜モデルにメソッドを持たせて呼び出すようにできないか検討しましょう。
- システムスペックのテストも書くようにしましょう。

### ４について
- やや使う上で癖があるように感じました。
- 申請をした際に受け取る側にアプリ上に通知が無かったり、チャットが投稿されても気づく要素がなかったり、その辺りも手を加えてあげるとより良くなると思います。
- チャットにおいてもLINEのように左右に表示されるブラウザと、左右に表示されないブラウザ（シークレットモード）があったので、修正できるようであれば修正しましょう。
- 現状のテストデータは本番時には削除しておきましょう。ただ誰も使っていないサービスという印象を与えてしまうと印象が良くないので、ユーザー獲得・サービスが使われている状態に向けて取り組むとより良い印象を与えると思います。
- 独自ドメインの取得も行いましょう。

---

以上がレビューになります。
引き続き開発頑張ってください。

**Comment by yoshi-dai** [comment]
レビューありがとうございます！
いただいたアドバイス活用させていただきます。
確認なのですが、MVPリリースに関しては一定の基準は満たせているという認識で大丈夫でしょうか？

**Comment by Tsuchiya2** [comment]
そうですね。。MVPリリースに関してはREADMEに記載されているMVPリリース基準は満たせているという認識で大丈夫です。

「就活において十分な技術力を示せる機能を実装しているか」に関しては、上記のコメントを参照してください。
